# Generated by Django 5.2.1 on 2025-05-22 03:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=250)),
                ('session_date', models.DateField(default=datetime.date.today)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('summarisation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementTemplates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('template_path', models.FileField(blank=True, null=True, upload_to='templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('INVESTIGATOR', 'Investigator'), ('INSURER', 'Insurer'), ('LEGAL TEAM', 'Legal Team')], default='INVESTIGATOR', max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='AudioRecordings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio_name', models.CharField(max_length=250)),
                ('length', models.DurationField()),
                ('size', models.IntegerField()),
                ('audio_path', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sessions')),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='template_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.statementtemplates'),
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('statement_content', models.TextField(blank=True, null=True)),
                ('interviewee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.interviewees')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('auditable_type', models.TextField()),
                ('auditable_id', models.IntegerField()),
                ('updated_content', models.TextField(blank=True, null=True)),
                ('event', models.CharField(choices=[('CREATED', 'created'), ('UPDATED', 'updated'), ('DELETED', 'deleted')], default='CREATED', max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
