# Generated by Django 5.2.1 on 2025-05-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statementtemplates',
            unique_together={('name', 'slug')},
        ),
    ]
