# Generated by Django 5.2.1 on 2025-05-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_statementtemplates_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementtemplates',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
