# Generated by Django 5.2 on 2025-05-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('INVESTIGATOR', 'Investigator'), ('INSURER', 'Insurer'), ('LEGAL TEAM', 'Legal Team')], default='INVESTIGATOR', max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
