# Generated by Django 5.2 on 2025-05-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_audits_event_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.users')),
            ],
        ),
    ]
