# Generated by Django 5.2 on 2025-05-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecordings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField()),
                ('statement_id', models.IntegerField()),
                ('audio_name', models.CharField(max_length=250)),
                ('length', models.DurationField()),
                ('size', models.IntegerField()),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('audio_path', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('auditable_type', models.TextField()),
                ('auditable_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('updated_content', models.TextField(blank=True, null=True)),
                ('event', models.CharField(choices=[('CREATED', 'created'), ('UPDATED', 'updated'), ('DELETED', 'deleted')], default='CREATED')),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_number', models.IntegerField()),
                ('case_type', models.TextField()),
                ('user_id', models.IntegerField()),
                ('status', models.TextField()),
                ('interviewee_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interviewees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=15)),
                ('language_pref', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('interviewee_id', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('session_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('interviewee_id', models.IntegerField()),
                ('audio_id', models.IntegerField()),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('updated_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementTemplates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('INVESTIGATOR', 'Investigator'), ('INSURER', 'Insurer'), ('LEGAL TEAM', 'Legal Team')], default='INVESTIGATOR')),
                ('organisation', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
