# Generated by Django 5.2 on 2025-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecordings',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
