# Generated by Django 5.2 on 2025-05-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_audiorecordings_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecordings',
            name='test',
        ),
    ]
