# Generated by Django 5.2.1 on 2025-05-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_audiorecordings_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audits',
            name='event',
            field=models.CharField(choices=[('CREATED', 'created'), ('UPDATED', 'updated'), ('DELETED', 'deleted')], default='CREATED', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('INVESTIGATOR', 'Investigator'), ('INSURER', 'Insurer'), ('LEGAL TEAM', 'Legal Team')], default='INVESTIGATOR', max_length=100),
        ),
    ]
